"""Add city_id

Revision ID: e6ea9ddf5420
Revises: b5649d3099ae
Create Date: 2024-10-17 19:17:04.329551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6ea9ddf5420"
down_revision: Union[str, None] = "b5649d3099ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("april", sa.Column("city_id", sa.Integer(), nullable=True))
    op.execute("UPDATE april SET city_id = 0")
    op.alter_column("april", sa.Column("city_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("april", "city_id")
    # ### end Alembic commands ###
